# Docker Compose for Seravo WordPress project template
#
# Start:
#   echo "SITE=wordpress" > .env
#   docker-compose run -e WP_USER_UID=$UID --service-ports --rm wordpress
# Or:
#   docker-compose up
#
# Access:
#   ssh vagrant@wordpress.local -o ForwardAgent=yes
#
# Clean up:
#   docker-compose down -v --remove-orphans
#   rm -rf .vagrant
#
# If container is not visible on your network, expose it with port
# bindings like:
#   - 80:80
#   - 443:443
#   - 22:22
# ...
#
version: '3'

services:
  wordpress:
    container_name: ${SITE:-wordpress}
    hostname: ${SITE:-wordpress}
    image: seravo/wordpress:development
    ports:
    - 80
    - 443
    - 22
    - 3306
    - 1337
    - 1338
    - 8080
    - 9000
    volumes:
    - wordpress:/data
    - .:/data/wordpress
    entrypoint: /sbin/swd_init

volumes:
  wordpress:
